staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com

tenderly-vnet-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://virtual.sepolia.us-east.rpc.tenderly.co/edaa3140-d48d-4bf8-873f-b9472d772a85

production-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
