# ==========================================================================
staging-settings:
  user-workflow:
    workflow-name: "link-credit-scoring-staging"
  workflow-artifacts:
    workflow-path: "./src/main.ts"
    config-path: "./config.staging.json"
    secrets-path: "./secrets.yaml"
# ==========================================================================
fork-settings:
  user-workflow:
    workflow-name: "link-credit-scoring-fork"
  workflow-artifacts:
    workflow-path: "./src/main.ts"
    config-path: "./config.staging.json"
    secrets-path: "./secrets.yaml"
# ==========================================================================
production-settings:
  user-workflow:
    workflow-name: "link-credit-scoring-production"
  workflow-artifacts:
    workflow-path: "./src/main.ts"
    config-path: "./config.production.json"
    secrets-path: "./secrets.yaml"
